package seniorproject;

import java.awt.*;
import javax.swing.*;
import java.awt.Font;
import java.awt.Color;
import java.util.Arrays;
import java.awt.event.*;
import java.security.Key;
import java.awt.Dimension;
import javax.swing.JFrame;
import java.awt.FlowLayout;
import javax.swing.ImageIcon;
import java.awt.BorderLayout;
import javax.swing.BorderFactory;
import javax.swing.SwingConstants;
import javax.swing.border.TitledBorder;
/**
 *
 * @author Santa Cardenas - Team Apollo Fall 2015 
 */
public class GUI extends javax.swing.JFrame 
{   
    public GUI() 
    {
        initComponents();
        
        // jLabel for the title
        jLabel1.setForeground(Color.white);
        jLabel1.setFont(new Font("Times New Roman", Font.BOLD, 45));
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        
        // jLabel for the vision
        jLabel2.setForeground(Color.white);
        jLabel2.setFont(new Font("Times New Roman", Font.BOLD, 25));
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        
        // jButton drivers will press to login
        jButton1.setText("Drivers");
        jButton1.setHorizontalAlignment(SwingConstants.CENTER);
        
        // jButton insurance companias will press to login
        jButton2.setText("Insurance Companies");
        jButton2.setHorizontalAlignment(SwingConstants.CENTER);
             
        // jButton legal representatives will press to login in
        jButton3.setText("Legal Representatives");
        jButton3.setHorizontalAlignment(SwingConstants.CENTER);

        // main screen size, location and title
        this.setSize(815,505);
        this.setResizable(false);
        this.setLocation(150,150);
	this.setTitle("Apollo GPS Dash Camera");
        
        // layout of main screen
        setLayout(null);
        setLayout(new BorderLayout());
        
        // Background image of main screen
        setContentPane(new JLabel(new ImageIcon(getClass().getResource("SP_image.png")))); 
	setLayout(new FlowLayout());
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome to Apollo");

        jLabel2.setText("Mobile experience capture wherever you are!");

        jLabel3.setText("Login");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jMenu1.setText("File");

        jMenuItem1.setText("Open");
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Delete");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem5.setText("Help");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("FAQ");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");

        jMenuItem7.setText("About");
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed
 
    public void ContentPaneMain(Container contentPane) 
    {
        // the box used to place the labels
        Box box1 = Box.createVerticalBox();
        
        // jLabel1 and jLabel2 add to the box
        box1.add(jLabel1);
        box1.add(jLabel2);
        
        // centering both labels
        jLabel1.setAlignmentX(Box.CENTER_ALIGNMENT);
        jLabel2.setAlignmentX(Box.CENTER_ALIGNMENT);
        
        // creating space between the labels
        box1.add(jLabel1);
        box1.add(Box.createRigidArea(new Dimension(0,225)));
        box1.add(jLabel2);
        
        // the box used to place the buttons
        Box box2 = Box.createHorizontalBox(); 
        
        // jButton1 and jButton2 add to the box
        box2.add(jButton1);
        box2.add(jButton2);
        box2.add(jButton3);
        
        // the box information 
        box2.setBorder(BorderFactory.createTitledBorder(null, "Login Options", 
                    TitledBorder.CENTER, TitledBorder.TOP, new Font("Times New "
                    + "Roman",Font.PLAIN,22),Color.white));
        
        // box layout and size
        this.add(box1, BorderLayout.CENTER);
        this.add(Box.createRigidArea(new Dimension(400,50)));
        this.add(box2, BorderLayout.PAGE_END);
    }
    
    private static void createAndShowGUI() 
    {
        //Create and set up the main window.
        JFrame frame1 = new JFrame("Apollo GPS GUI");
        frame1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
 
        //Create and set up the content pane.
        GUI gui = new GUI();
        gui.ContentPaneMain(frame1.getContentPane());

        //Display the window.
        frame1.pack();
        frame1.setVisible(true);
    }

public static void main(String args[]) 
  {
        //Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
             createAndShowGUI();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}